#!/bin/bash
# 
# Recommended:
# 
# mkdir -p ~/backup
cd ~/backup
#

# Check if backup file exist
if [ ! -f substrate-data.tar ]; then
    echo "File not found!"
    echo "Downloading"
    # Download the tarball
    wget https://polkastats.io/downloads/substrate-data.tar
fi

if [ ! -f substrate-data.tar ]; then
    echo "File not found!"
    echo "Abort"
    exit 1
fi

# Stop all cointainers
docker stop polkastats-backend_crawler_1
docker stop polkastats-backend_phragmen_1
docker stop polkastats-backend_graphql-engine_1
docker stop polkastats-backend_postgres_1

# This one is mandatory to be stopped
docker stop polkastats-backend_substrate-node_1
sleep 5

if [ $(docker inspect -f '{{.State.Running}}' polkastats-backend_substrate-node_1) = "true" ]; then 
    echo "Substrate node still running"
    exit 1
else 
    echo "Substrate node stopped"
    echo "Starting the restoration"
fi

## Restore
docker run --rm --volumes-from polkastats-backend_substrate-node_1 -v $(pwd):/backup ubuntu bash -c "cd /data && tar xvf /backup/substrate-data.tar --strip 1"

echo ""
echo "Restoring backup finished"
echo ""