#!/bin/bash
docker stop polkastats-backend_crawler_1
docker stop polkastats-backend_postgres_1
docker stop polkastats-backend_graphql-engine_1

docker rm polkastats-backend_crawler_1
docker rm polkastats-backend_postgres_1
docker rm polkastats-backend_graphql-engine_1

docker rmi polkastats-backend:latest

docker volume rm polkastats-backend_db-data

