name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t polkastats/polkastats-crawlers . -f docker/polkastats-backend/backend/Dockerfile
