name: Gitlab

on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
  workflow_dispatch:

jobs:
  run-gitlab-pipeline:
    name: Run gitlab pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST -F token=${{ secrets.GITLAB_TOKEN }} -F ref=develop -F variables[BRANCH_NAME]=${{ steps.extract_branch.outputs.branch }} https://gitlab.usetech.ru/api/v4/projects/334/trigger/pipeline
